### ISSUE TITLE
Any suggestions for improving the speed and accuracy of facial recognition?

### ISSUE THREAD

**Issue by AzwadFawadHasan** [LShun/face-recognition-low-res#1]
I'm using svm version and  ai as the detection mode here. The accuracy here is a bit off as sometimes even completely different people are falsely recognized as someone else. Also it's taking a bit too long for recognizing each image.
Summary
==========================
Total pictures 48
Faces identified correctly:  25
Faces identified wrongly:  13
Faces not identified:  10
Absolute Accuracy (correct / [correct + incorrect + not detected]) * 100%: 
52.0 %
Detection Accuracy [(correct + incorrect) / total] * 100%: 
79.17 %
END, time taken:  6795.78 seconds
Avg. secs. per picture:  141.58 seconds
==========================

Process finished with exit code 0

**Comment by LShun** [comment]
Hi, I noticed that you have a total faces of 48 which seems to be more than the 30 faces used in the original project. I assume you are using your own dataset. This will introduce uncertainties, as different pictures have different features and some are "easier", whereas others are "harder" to detect correctly (or even be able to be detected at all). For example, poorly lit images, misaligned images, or even pictures which in low resolution, are missing certain key features (i.e. nose) can be much more challenging.

For the excessive time taken per picture, this can be caused by a few factors, which include system performance (at the point the project was done, this was likely done on a Ryzen 5 2600), the size of the pictures (in our case, we used 30x30), dataset size, and so forth. As a suggestion, perhaps start with just two face and a few pictures, see how long does it takes. Try to adjust the resolution and scale it down, to see if the speed improves. Note that without a GPU or a very good CPU, it is expected for it to be slow.

As conclusion, I think you will have to play around with the size of the dataset and image size, play around with them to see if you can drop the time spent, to achieve a reasonable performance level. I wish you the best of luck.
